// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3JUGS6ZLGyJlhvLUGhN84xtbYsFh0Y-E',
    appId: '1:722629128866:web:83ca409006d67b7b0e1dfb',
    messagingSenderId: '722629128866',
    projectId: 'cancer-detection-app-ca15a',
    authDomain: 'cancer-detection-app-ca15a.firebaseapp.com',
    storageBucket: 'cancer-detection-app-ca15a.firebasestorage.app',
    measurementId: 'G-FV8NR4HKJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPCl2C-6Tb61POMkVQwNlZW83D9JsygVA',
    appId: '1:722629128866:android:172c67104d31b9540e1dfb',
    messagingSenderId: '722629128866',
    projectId: 'cancer-detection-app-ca15a',
    storageBucket: 'cancer-detection-app-ca15a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR6Sgnn3GvYOE-1cGg_fq_PiuiR-uXeyo',
    appId: '1:722629128866:ios:77f883f1517151e70e1dfb',
    messagingSenderId: '722629128866',
    projectId: 'cancer-detection-app-ca15a',
    storageBucket: 'cancer-detection-app-ca15a.firebasestorage.app',
    iosBundleId: 'com.example.cancerDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR6Sgnn3GvYOE-1cGg_fq_PiuiR-uXeyo',
    appId: '1:722629128866:ios:77f883f1517151e70e1dfb',
    messagingSenderId: '722629128866',
    projectId: 'cancer-detection-app-ca15a',
    storageBucket: 'cancer-detection-app-ca15a.firebasestorage.app',
    iosBundleId: 'com.example.cancerDetectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3JUGS6ZLGyJlhvLUGhN84xtbYsFh0Y-E',
    appId: '1:722629128866:web:af537ab5daf1596c0e1dfb',
    messagingSenderId: '722629128866',
    projectId: 'cancer-detection-app-ca15a',
    authDomain: 'cancer-detection-app-ca15a.firebaseapp.com',
    storageBucket: 'cancer-detection-app-ca15a.firebasestorage.app',
    measurementId: 'G-70CRPS6MHE',
  );
}
